### ISSUE TITLE
Documentation? 

### ISSUE THREAD

**Issue by multinucliated** [linkedin/detext#33]
I can't find much documentation about it.

**Comment by sbourke** [comment]
It could be useful to have some examples on open datasets to build a model run from start to finish. I'm going through the code to work out what does what. 

But generally looks really interesting.

**Comment by multinucliated** [comment]
@sbourke  that's correct, even we can submit or provide sample codes if we have something to start with.

**Comment by xwli-chelsea** [comment]
Thanks for the comments @multinucliated @sbourke ! Pease refer to the [TRAINING.md](https://github.com/linkedin/detext/blob/master/TRAINING.md) for details on the training data format/preparation and training params. 

We are working on to add some detailed hands-on tutorial notebooks with some public datasets to show users end-to-end training examples including data preparation. Please stay tuned! :)

**Comment by vlasvlasvlas** [comment]
this, is important. thanks!

**Comment by StarWang** [comment]
Hi guys, we've hosted a tutorial on how to use DeText in a KDD workshop. Helpful materials (notebooks, slides, etc.) can be found at the [workshop page](https://sites.google.com/view/kdd20tutorial-deepsnr)

**Comment by xwli-chelsea** [comment]
Closing this as examples and references are added. Thanks!
