### ISSUE TITLE
Dependency issue while testing

### ISSUE THREAD

**Issue by glitch401** [linkedin/detext#34]
Following the installation instructions,
I'd setup a new venv and had successfully run the setup step `python setup.py develop`
Unfortunately, while running a sample test using `pytest`, there seems to be `ModuleNotFoundError` for its dependency on tensorflow.
While checking in the same venv, i get the exact version of Tf installed as the requirement in `setup.py`
[error trace](https://pastebin.com/WDj5xmHn)
![image](https://user-images.githubusercontent.com/26926571/88886501-408a9380-d258-11ea-9498-a5b2bce9512a.png)

Although model training toy example using `bash run_detext.sh`  at `test/resources` seems to be [working fine](https://pastebin.com/8uXmcbsW)

**Comment by StarWang** [comment]
Hi @glitch401 , can you try running `python -m pytest test` as a workaround?

I'm looking into the reason why your executing pytest directly does not work.

**Comment by StarWang** [comment]
No response from user
