### ISSUE TITLE
Can it rank the documents semantically without pretraining

### ISSUE THREAD

**Issue by deepankar27** [linkedin/detext#36]
Hello Team,

Say I don't have any query to documents mapped, I have only documents will it rank the documents semantically based on add hoc questions? I have went through your documentation but didn't find such feature listed.

Thanks in advance.

**Comment by StarWang** [comment]
Hi @deepankar27 , given that your use case is "rank the documents given ad hoc questions", you will still need a dataset that has query to documents mapping. The key is that your training and inference scenario need to be consistent

**Comment by luke4u** [comment]
@StarWang , thanks for the explanation. just to confirm my understanding.  We still need to retrain the model with a dataset containing query to document mapping, before inference?

**Comment by StarWang** [comment]
@luke4u Yes

**Comment by aradhanacha** [comment]
@luke4u do you have any sample code for ranking the data..Documentation doesnt have much explanation

**Comment by StarWang** [comment]
Hi @aradhanacha , you can find the scoring code for a trained model in a hands-on tutorial [here](https://drive.google.com/file/d/1PRBrqV52TAL1LJwcati7BYywYDfCp2J9/view?usp=sharing)

**Comment by aradhanacha** [comment]
Thanks @StarWang I will try this code.
Can you also suggest me how many examples should suffice for query,document ranking task..As in real world implementations its difficult to get actual ranking of document for query.do you have any sample training dataset for this task?

**Comment by StarWang** [comment]
@aradhanacha It really depends on the complexity of your task, your data cleanness, etc.. The only recommendation is that you have to try.

For datasets, you can try locating available datasets from ranking related papers. Robust04 and ClueWeb09-B are classic datasets for document retrieval, which you can use for ranking as well

**Comment by aradhanacha** [comment]
Thanks @StarWang
