### ISSUE TITLE
Query the data. 

### ISSUE THREAD

**Issue by yaskh** [linkedin/detext#39]
Hey!
Once i have trained the model with custom data, is there a method/function to query the ingested data? 
Thanks!

**Comment by xwli-chelsea** [comment]
Hi, Do you mean running inference with the trained model?

**Comment by yaskh** [comment]
Hey!
Yes i need that.
Also is there a documentation that i can refer to for using the trained model? 
Thanks!

**Comment by xwli-chelsea** [comment]
Added a classification demo notebook. There's an example at the end for using the trained model for inference. Another ranking demo can be found in our [KDD workshop webpage](https://sites.google.com/view/kdd20tutorial-deepsnr). 
Related: #33 
Thanks!
