### ISSUE TITLE
Sequence Completion

### ISSUE THREAD

**Issue by burakisikli** [linkedin/detext#50]
Hi,
In the Linkedin engineering blog, it's said that "Currently, DeText can support ranking, classification, and sequence completion—3 of the 6 representative tasks". I couldn't see any instructions or training examples for sequence completion(query auto completion). Can you help me with this?

**Comment by StarWang** [comment]
Hi @burakisikli , you can visit our KDD tutorial website for python notebook on query auto completion [here](https://sites.google.com/view/kdd20tutorial-deepsnr)

**Comment by avaranovich** [comment]
@StarWang I am interested in this scenario as well, but the link does not seem to be available anymore. Can you share the notebook here on GitHub? Would be useful.
