### ISSUE TITLE
LIBERT model

### ISSUE THREAD

**Issue by kuatroka** [linkedin/detext#54]
Hi, is your LIBERT model available through Huggingface or some other platform to download and use? Thanks

**Comment by StarWang** [comment]
@xwli-chelsea to provide context

**Comment by xwli-chelsea** [comment]
Thanks @StarWang 
Hi @kuatroka , currently we're not planning to release the LiBERT models as they are pretrained with internal data. But feel free to use any open source BERT models with DeText :) Thanks
